[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["python -m venv .venv", "source .venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
